apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bookstore
  name: bookstore
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bookstore
  template:
    metadata:
      labels:
        app: bookstore
    spec:
      containers:
      - image: 408579600952.dkr.ecr.us-east-1.amazonaws.com/onlinebook1:BUILD_NUMBER
        name: bookstore
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bookstore
  name: bookstore
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: bookstore
  type: NodePort
